import { conceptById } from '../data/concepts'
import { philosopherById } from '../data/philosophers'
import { passages } from '../data/texts'
import type { CompareQuestion, Domain, Passage, Position } from '../model/types'
import { detectConcepts } from './lexicon'

/** Framework-based sketch for questions without a curated comparison. Always labelled as interpretation. */
export function sketchComparison(question: string, philosopherIds: string[]): CompareQuestion {
  const cs = detectConcepts(question, 6)
  const positions: Position[] = philosopherIds.map((id) => {
    const p = philosopherById[id]
    const overlap = p.concepts.filter((c) => cs.includes(c) || cs.some((q) => conceptById[q]?.related.includes(c)))
    const lens = (overlap.length ? overlap : p.concepts).slice(0, 2).map((c) => conceptById[c])
    const passage = passages.find((x) => x.author === id && x.source === 'quotation' && x.concepts.some((c) => overlap.includes(c))) ??
      passages.find((x) => x.author === id && x.source === 'quotation')
    return {
      philosopher: id,
      stance: 'Sketch',
      headline: `Through the lens of ${lens.map((l) => l?.name).filter(Boolean).join(' and ')}.`,
      reasoning: [
        `${p.name.split(' ').slice(-1)[0]}’s guiding project: ${p.signature.charAt(0).toLowerCase() + p.signature.slice(1)}`,
        ...lens.filter(Boolean).map((l) => `Applied here, ${l!.name.toLowerCase()} suggests: ${l!.definition.charAt(0).toLowerCase() + l!.definition.slice(1)}`),
        overlap.length ? `This question touches concepts central to their work (${overlap.map((o) => conceptById[o]?.name).join(', ')}).` : 'This question is not one they address directly — treat this column with extra caution.',
      ],
      support: [
        {
          source: 'interpretation',
          text: 'Generated by the Agora reasoning engine from this philosopher’s core commitments. It is not a claim about what they actually wrote on this question.',
        },
        ...(passage ? [{ source: 'quotation' as const, passageId: passage.id, text: 'Related passage (not about this question directly)', citation: passage.locator }] : []),
      ],
      concepts: overlap.length ? overlap : p.concepts.slice(0, 3),
    }
  })
  const names = philosopherIds.map((i) => philosopherById[i].name.split(' ').slice(-1)[0])
  return {
    id: 'custom',
    question,
    domain: (cs[0] ? conceptById[cs[0]].domain : 'Ethics') as Domain,
    positions,
    keyDifference: `This is a generated sketch. The deepest disagreement among ${names.join(', ')} is likely to concern where authority comes from — reason, consequences, experience, history, or choice. Verify each column against the texts before relying on it.`,
    axes: [
      {
        label: 'Starting point',
        values: Object.fromEntries(philosopherIds.map((id) => [id, philosopherById[id].concepts[0] ? conceptById[philosopherById[id].concepts[0]]?.name ?? '—' : '—'])),
      },
    ],
  }
}

export function interpretPassage(p: Passage): { claim: string; project: string; connections: string[]; question: string } {
  const ph = philosopherById[p.author]
  const cs = p.concepts.map((c) => conceptById[c]).filter(Boolean)
  return {
    claim: cs[0]
      ? `The passage is best read as a contribution to ${cs[0].name.toLowerCase()}: ${cs[0].definition.charAt(0).toLowerCase() + cs[0].definition.slice(1)}`
      : 'The passage advances a central claim of this work.',
    project: `It serves ${ph.name.split(' ').slice(-1)[0]}’s larger project — ${ph.signature.charAt(0).toLowerCase() + ph.signature.slice(1)}`,
    connections: cs.slice(1, 4).map((c) => `${c.name}: ${c.note}`),
    question: p.source === 'quotation'
      ? 'Read the sentence again without the context. What does it seem to claim on its own — and does the context change that?'
      : 'This is a summary. Before citing it, what would you need to check in the original text?',
  }
}
